
name: CI-serviceOne

on:
  push:
    branches: [ "main" ]
    paths:
      - 'src/service-one/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'src/service-one/**'

jobs:

  ServiceOne:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Test
      run: bazel test //src/service-one/...  --test_output=errors   

    - name: Build
      run: bazel build //src/service-one
      
    - name: Create Docker image
      run: bazel run //src/service-one:image  
