
name: CI-serviceTwo

on:
  push:
    branches: [ "main" ]
    paths:
      - 'src/service-two/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'src/service-two/**'

jobs:

  ServiceTwo:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Test
      run: bazel test //src/service-two/...  --test_output=errors    

    - name: Build
      run: bazel build //src/service-two
    
    - name: Create Docker image
      run: bazel run //src/service-two:image

